{% set name = "aesara-theano-fallback" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aesara_theano_fallback-{{ version }}.tar.gz
  sha256: fd4b0dd4848f0380c616e8e8a20566aa21b33a5f504ee9a0461cacf3f14dac5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6

test:
  imports:
    - aesara_theano_fallback
    - aesara_theano_fallback.tensor
    - aesara_theano_fallback.graph
  commands:
    - pip check
  requires:
    - pip
    - aesara

about:
  home: https://github.com/exoplanet-dev/aesara-theano-fallback
  summary: Striving towards backwards compatibility with the Theano -> Aesara transition
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dfm
